name: deps
version: 0.0.3
description: Simple, flexible and opinionated Dependency Injection
repository: https://github.com/tom-010/dart-dependencies
environment: 
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  test: ^1.16.0